steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/resource-collector', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/resource-collector']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'jobs'
    - 'create'
    - 'resource-job'
    - '--image'
    - 'gcr.io/$PROJECT_ID/resource-collector'
    - '--region'
    - 'asia-northeast3'
    - '--set-env-vars'
    - 'PROJECT_ID=$PROJECT_ID,BUCKET_NAME=${_BUCKET_NAME}'
    - '--task-timeout'
    - '1800'
    - '--memory'
    - '1Gi'
    - '--max-retries'
    - '1'

options:
  logging: CLOUD_LOGGING_ONLY