steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_NAME}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'jobs'
    - 'create'
    - 'resource-job'
    - '--image'
    - '${_IMAGE_NAME}'
    - '--region'
    - 'asia-northeast3'
    - '--set-env-vars'
    - 'PROJECT_ID=$PROJECT_ID,BUCKET_NAME=${_BUCKET_NAME}'
    - '--task-timeout'
    - '1800'
    - '--memory'
    - '1Gi'
    - '--max-retries'
    - '1'

substitutions:
  _IMAGE_NAME: 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cloud-build/resource-collector:latest'
  _BUCKET_NAME: 'resource-collector'

options:
  logging: CLOUD_LOGGING_ONLY