steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_ARTIFACT_REGISTRY}/resource-collector:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_ARTIFACT_REGISTRY}/resource-collector:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'jobs'
    - 'create'
    - 'resource-job'
    - '--image'
    - '${_ARTIFACT_REGISTRY}/resource-collector:latest'
    - '--region'
    - 'asia-northeast3'
    - '--set-env-vars'
    - 'PROJECT_ID=$PROJECT_ID,BUCKET_NAME=${_BUCKET_NAME}'
    - '--task-timeout'
    - '1800'
    - '--memory'
    - '1Gi'
    - '--max-retries'
    - '1'

substitutions:
  _ARTIFACT_REGISTRY: 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cloud-build'
  _BUCKET_NAME: 'resource-collector'

options:
  logging: CLOUD_LOGGING_ONLY